### ISSUE TITLE
No {class_}_species_picked.txt

### ISSUE THREAD

**Issue by chengdongqiang** [f-kretschmer/bertax_training#7]
Hi, I hope to repeat this training process, but I got this error.  Could you please help me to find out what's the _cpecies_picked.txt looks. Or could you provide all the input files that I can run under the genomic DNA situation? Thanks. 
###########################
Traceback (most recent call last):
  File "/home/cheng/miniconda3/envs/machine_learning/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/cheng/miniconda3/envs/machine_learning/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/CHENG/work_machine_learning/bertax_training/models/bert_nc.py", line 97, in <module>
    fragments, y, species = load_fragments(
  File "/data/CHENG/work_machine_learning/bertax_training/preprocessing/generate_data.py", line 563, in load_fragments
    open(os.path.join(fragments_dir, f'{class_}_species_picked.txt')).readlines()])
FileNotFoundError: [Errno 2] No such file or directory: './Viruses_species_picked.txt'

**Comment by f-kretschmer** [comment]
Hi, which data did you use? For our deposited data (https://osf.io/qg6mv/, "pretraining_dataset" in this case), fragments for input (which include the `species_picked.txt` files) can be converted from the fasta files there. These (multi)fasta files contain headers, which consist of a fragment's associated species' TaxID and a concurrent index. (Example `>1937004 2`: "1937004" is the species TaxID here). The `species_picked.txt` files are simply (ordered) lists of these TaxIDs. The most simple way to obtain these would be to use the scripts described at the bottom of this repository's README; specifically `preprocessing/fasta2fragments.py`, with the first argument being the fasta file for input, the second specifying a file prefix for the output files. I hope this answers your question; otherwise please reopen the issue!

**Comment by flomock** [comment]
I updated the readme, maybe the Data preparation process is clearer now.
